# Generated by Django 4.1.4 on 2022-12-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
